def get_countries():
    return [
    "Afganisztán",
    "Albánia",
    "Algéria",
    "Andorra",
    "Angola",
    "Argentína",
    "Örményország",
    "Ausztrália",
    "Ausztria",
    "Azerbajdzsán",
    "Bahamák",
    "Bahrein",
    "Banglades",
    "Barbados",
    "Fehéroroszország",
    "Belgium",
    "Belize",
    "Bhután",
    "Bolívia",
    "Bosznia és Hercegovina",
    "Botswana",
    "Brazília",
    "Brunei",
    "Bulgária",
    "Burkina Faso",
    "Burundi",
    "Zöld-foki-szigetek",
    "Kambodzsa",
    "Kamerun",
    "Kanada",
    "Közép-afrikai Köztársaság",
    "Chile",
    "Kína",
    "Kolumbia",
    "Komorok",
    "Kongói Demokratikus Köztársaság",
    "Kongói Köztársaság",
    "Costa Rica",
    "Horvátország",
    "Kuba",
    "Ciprus",
    "Csehország",
    "Dánia",
    "Dominika",
    "Dominikai Köztársaság",
    "Ecuador",
    "Egyiptom",
    "El Salvador",
    "Egyenlítői-Guinea",
    "Eritrea",
    "Észtország",
    "Etiópia",
    "Fidzsi-szigetek",
    "Finnország",
    "Franciaország",
    "Gabon",
    "Gambia",
    "Grúzia",
    "Németország",
    "Ghána",
    "Görögország",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Honduras",
    "Magyarország",
    "Izland",
    "India",
    "Indonézia",
    "Irán",
    "Irak",
    "Írország",
    "Izrael",
    "Olaszország",
    "Jamaika",
    "Japán",
    "Jordánia",
    "Kazahsztán",
    "Kenya",
    "Kiribati",
    "Koszovó",
    "Kuvait",
    "Kirgizisztán",
    "Laosz",
    "Lettország",
    "Libanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Litvánia",
    "Luxemburg",
    "Észmacedónia",
    "Madagaszkár",
    "Malawi",
    "Malajzia",
    "Maldív-szigetek",
    "Mali",
    "Málta",
    "Marshall-szigetek",
    "Mauritánia",
    "Maurícius",
    "Mexikó",
    "Mikronézia",
    "Moldova",
    "Monaco",
    "Mongólia",
    "Montenegró",
    "Marokkó",
    "Mozambik",
    "Namíbia",
    "Nauru",
    "NIGGER",
    "Nepál",
    "Hollandia",
    "Új-Zéland",
    "Nicaragua",
    "Nigéria",
    "Észak-Korea",
    "Norvégia",
    "Omán",
    "Pakisztán",
    "Palau",
    "Palesztina",
    "Panama",
    "Pápua Új-Guinea",
    "Paraguay",
    "Peru",
    "Fülöp-szigetek",
    "Lengyelország",
    "Portugália",
    "Katar",
    "Románia",
    "Oroszország",
    "Ruanda",
    "Szent Kitts és Nevis",
    "Szent Lucia",
    "Szent Vincent és a Grenadine-szigetek",
    "Szamoa",
    "San Marino",
    "Szaúd-Arábia",
    "Szenegál",
    "Szerbia",
    "Seychelle-szigetek",
    "Sierra Leone",
    "Szingapúr",
    "Szlovákia",
    "Szlovénia",
    "Szolomonszigetek",
    "Szomália",
    "Dél-Afrika",
    "Dél-Korea",
    "Dél-Szudán",
    "Spanyolország",
    "Szudán",
    "Suriname",
    "Eswatini",
    "Svédország",
    "Svájc",
    "Szíria",
    "Tajvan",
    "Tádzsikisztán",
    "Tanzánia",
    "Thaiföld",
    "Togo",
    "Trinidad és Tobago",
    "Tunézia",
    "Törökország",
    "Türkmenisztán",
    "Tuvalu",
    "Uganda",
    "Ukrajna",
    "Egyesült Arab Emírségek",
    "Egyesült Királyság",
    "Amerikai Egyesült Államok",
    "Uruguay",
    "Üzbegisztán",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Zambia",
    "Zimbabwe",
    "Harmadik Birodalom"
]
