def get_countries():
    return [
        "afganisztán",
        "albánia",
        "algéria",
        "andorra",
        "angola",
        "argentina",
        "örményország",
        "ausztrália",
        "ausztria",
        "azerbajdzsán",
        "bahamák",
        "bahrein",
        "banglades",
        "barbados",
        "fehéroroszország",
        "belgium",
        "belize",
        "bhután",
        "bolívia",
        "bosznia és hercegovina",
        "botswana",
        "brazília",
        "brunei",
        "bulgária",
        "burkina faso",
        "burundi",
        "zöld-foki-szigetek",
        "kambodzsa",
        "kamerun",
        "kanada",
        "közép-afrikai köztársaság",
        "chile",
        "kína",
        "kolumbia",
        "komorok",
        "kongói demokratikus köztársaság",
        "kongói köztársaság",
        "costa rica",
        "horvátország",
        "kuba",
        "ciprus",
        "csehország",
        "dánia",
        "dominika",
        "dominikai köztársaság",
        "ecuador",
        "egyiptom",
        "el salvador",
        "egyenlítői-guinea",
        "eritrea",
        "észtország",
        "etiópia",
        "fidzsi-szigetek",
        "finnország",
        "franciaország",
        "gabon",
        "gambia",
        "grúzia",
        "németország",
        "ghána",
        "görögország",
        "guatemala",
        "guinea",
        "guinea-bissau",
        "guyana",
        "honduras",
        "magyarország",
        "izland",
        "india",
        "indonézia",
        "irán",
        "irak",
        "írország",
        "izrael",
        "olaszország",
        "jamaika",
        "japán",
        "jordánia",
        "kazahsztán",
        "kenya",
        "kiribati",
        "koszovó",
        "kuwait",
        "kirgizisztán",
        "laosz",
        "lettország",
        "libanon",
        "lesotho",
        "libéria",
        "libya",
        "liechtenstein",
        "litvánia",
        "luxemburg",
        "észmacedónia",
        "madagaszkár",
        "malawi",
        "malajzia",
        "maldív-szigetek",
        "mali",
        "málta",
        "marshall-szigetek",
        "mauritánia",
        "maurícius",
        "mexikó",
        "mikronézia",
        "moldova",
        "monaco",
        "mongólia",
        "montenegró",
        "marokkó",
        "mozambik",
        "namíbia",
        "nauru",
        "nigger",
        "nepál",
        "hollandia",
        "új-zéland",
        "nicaragua",
        "nigéria",
        "észak-korea",
        "norvégia",
        "omán",
        "pakisztán",
        "palau",
        "palesztina",
        "panama",
        "pápua új-guinea",
        "paraguay",
        "peru",
        "fülöp-szigetek",
        "lengyelország",
        "portugália",
        "katar",
        "románia",
        "oroszország",
        "ruanda",
        "szent kitts és nevis",
        "szent lucia",
        "szent vincent és a grenadine-szigetek",
        "szamoa",
        "san marino",
        "szaúd-arábia",
        "szenegál",
        "szerbia",
        "seychelle-szigetek",
        "sierra leone",
        "szingapúr",
        "szlovákia",
        "szlovénia",
        "szolomonszigetek",
        "szomália",
        "dél-afrika",
        "dél-korea",
        "dél-szudán",
        "spanyolország",
        "szudán",
        "suriname",
        "eswatini",
        "svédország",
        "svájc",
        "szíria",
        "tajvan",
        "tádzsikisztán",
        "tanzánia",
        "thaiföld",
        "togo",
        "trinidad és tobago",
        "tunézia",
        "törökország",
        "türkmenisztán",
        "tuvalu",
        "uganda",
        "ukrajna",
        "egyesült arab emírségek",
        "egyesült királyság",
        "amerikai egyesült államok",
        "uruguay",
        "üzbegisztán",
        "vanuatu",
        "venezuela",
        "vietnam",
        "zambia",
        "zimbabwe",
        "harmadik birodalom"
    ]
